// ============================================================
// AI SKIN INTELLIGENCE
// ANALYSIS RESULT COMPONENT
// ============================================================
//
// Responsibilities:
//   1. Display the CNN skin concern prediction
//   2. Display model confidence
//   3. Display all six class probabilities
//   4. Display user's personalization information
//   5. Display the Groq-generated personalized assessment
//   6. Display practical recommendations
//
// Backend response used by this component:
//
// {
//   predicted_class,
//   confidence,
//   probabilities,
//   age,
//   gender,
//   skin_type,
//   personal_query,
//   routine_7_day,
//   recommended_products
// }
//
// ============================================================

import React from 'react';

import {
  Activity,
  ShieldAlert,
  CheckCircle2,
  UserRound,
  MessageSquareText,
  Sparkles,
  Info,
} from 'lucide-react';


// ============================================================
// COMPONENT
// ============================================================

export default function AnalysisResult({
  result,
}) {

  // ==========================================================
  // NO ANALYSIS AVAILABLE
  // ==========================================================
  //
  // This is displayed before the user runs a diagnostic.
  // ==========================================================

  if (!result) {

    return (

      <div className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm flex flex-col items-center justify-center text-center text-slate-400 h-full min-h-[300px]">

        <Activity className="w-10 h-10 text-emerald-600/40 mb-3" />

        <h3 className="text-sm font-bold text-slate-700">
          Facial Diagnostics Ready
        </h3>

        <p className="text-xs text-slate-400 max-w-xs mt-1 leading-relaxed">
          Upload or capture a close-up photo and provide your
          personal details to generate a personalized skincare
          analysis.
        </p>

      </div>

    );
  }


  // ==========================================================
  // 1. PRIMARY AI PREDICTION
  // ==========================================================
  //
  // predicted_class is generated by the CNN model.
  //
  // Example:
  //   acne
  //   blackheads
  //   clear skin
  //   dark spots
  //   puffy eyes
  //   wrinkles
  // ==========================================================

  const primaryConcern =
    result.predicted_class ||
    'Unknown';


  // ==========================================================
  // 2. MODEL CONFIDENCE
  // ==========================================================
  //
  // Backend stores confidence as a decimal:
  //
  //     0.9959
  //
  // Frontend displays:
  //
  //     99.6%
  // ==========================================================

  const confidence =
    Number(result.confidence) || 0;


  const formattedConfidence =
    (confidence * 100).toFixed(1);


  // ==========================================================
  // 3. PROBABILITY DISTRIBUTION
  // ==========================================================
  //
  // IMPORTANT:
  // We do NOT create artificial fallback probabilities here.
  //
  // The values shown to the user should come directly from
  // the CNN model through the FastAPI backend.
  // ==========================================================

  const probabilities =
    result.probabilities &&
    typeof result.probabilities === 'object'
      ? result.probabilities
      : {};


  // ==========================================================
  // 4. EXPECTED MODEL CLASSES
  // ==========================================================
  //
  // The current facial skin model contains six classes.
  //
  // Keeping the order consistent makes the UI easier to read.
  // ==========================================================

  const expectedClasses = [
    'acne',
    'blackheads',
    'clear skin',
    'dark spots',
    'puffy eyes',
    'wrinkles',
  ];


  // ==========================================================
  // 5. BUILD SAFE PROBABILITY LIST
  // ==========================================================
  //
  // Only values returned by the backend are displayed.
  //
  // Missing values are shown as 0 rather than inventing
  // predictions.
  // ==========================================================

  const probabilityEntries =
    expectedClasses.map(
      (concern) => {

        const value =
          Number(
            probabilities[concern]
          ) || 0;

        return {
          concern,
          probability: value,
        };
      }
    );


  // ==========================================================
  // 6. PERSONALIZED LLM RESPONSE
  // ==========================================================
  //
  // The backend sends the Groq-generated routine in:
  //
  // result.routine_7_day
  //
  // The routine contains sections such as:
  //
  // ### Personalized Assessment
  // ### What You Should Do
  // ### Product Approach
  // ### 7-Day Personalized Routine
  // ### Important Precautions
  //
  // We extract the first two sections for the dashboard.
  // ==========================================================

  const routineText =
    typeof result.routine_7_day === 'string'
      ? result.routine_7_day
      : '';


  // ==========================================================
  // 7. EXTRACT PERSONALIZED ASSESSMENT
  // ==========================================================

  const assessmentMatch =
    routineText.match(
      /### Personalized Assessment\s*([\s\S]*?)(?=### What You Should Do|### Product Approach|### 7-Day Personalized Routine|### Important Precautions|$)/i
    );


  const personalizedAssessment =
    assessmentMatch
      ? assessmentMatch[1].trim()
      : 'The AI-generated personalized assessment is not available for this scan.';


  // ==========================================================
  // 8. EXTRACT PRACTICAL ACTIONS
  // ==========================================================

  const actionMatch =
    routineText.match(
      /### What You Should Do\s*([\s\S]*?)(?=### Product Approach|### 7-Day Personalized Routine|### Important Precautions|$)/i
    );


  const personalizedAction =
    actionMatch
      ? actionMatch[1].trim()
      : 'Follow the personalized skincare routine generated for your skin concern and user context.';


  // ==========================================================
  // 9. DETERMINE WHETHER PRIMARY CONDITION IS CLEAR SKIN
  // ==========================================================

  const isClearSkin =
    primaryConcern
      .toLowerCase()
      .trim() === 'clear skin';


  // ==========================================================
  // UI
  // ==========================================================

  return (

    <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-5 h-full flex flex-col">


      {/* ======================================================
          HEADER
          ====================================================== */}

      <div className="flex items-center justify-between pb-3 border-b border-slate-100">

        <div>

          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
            FACIAL DIAGNOSTICS
          </span>

          <h3 className="text-base font-extrabold text-slate-900">
            Skin Concern Analysis
          </h3>

        </div>


        {/* Model confidence */}

        <span className="text-xs font-bold text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">

          {formattedConfidence}%
          {' '}
          Confidence

        </span>

      </div>


      {/* ======================================================
          PRIMARY CONDITION
          ======================================================
          
          This is the class with the highest probability from
          the CNN model.
          ====================================================== */}

      <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 flex items-center justify-between">

        <div>

          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-0.5">
            Primary Detected Concern
          </span>

          <span className="text-xl font-black text-slate-900 capitalize block">
            {primaryConcern}
          </span>

        </div>


        {isClearSkin ? (

          <CheckCircle2 className="w-6 h-6 text-emerald-600" />

        ) : (

          <ShieldAlert className="w-6 h-6 text-amber-500" />

        )}

      </div>


      {/* ======================================================
          USER PERSONALIZATION CONTEXT
          ======================================================
          
          These values are provided by the user and are NOT
          predicted by the facial concern CNN model.
          ====================================================== */}

      <div className="bg-emerald-50/70 border border-emerald-100 rounded-xl p-4 space-y-3">

        <div className="flex items-center gap-2">

          <UserRound className="w-4 h-4 text-emerald-600" />

          <span className="text-[10px] font-black text-emerald-700 uppercase tracking-wider">
            Personalized User Context
          </span>

        </div>


        {/* ----------------------------------------------------
            AGE / SKIN TYPE / GENDER
            ---------------------------------------------------- */}

        <div className="grid grid-cols-3 gap-2">


          {/* Age */}

          <div className="bg-white rounded-lg border border-emerald-100 p-2">

            <span className="block text-[9px] uppercase font-bold text-slate-400">
              Age
            </span>

            <span className="text-xs font-black text-slate-800">
              {result.age ?? 'N/A'}
            </span>

          </div>


          {/* Skin Type */}

          <div className="bg-white rounded-lg border border-emerald-100 p-2">

            <span className="block text-[9px] uppercase font-bold text-slate-400">
              Skin Type
            </span>

            <span className="text-xs font-black text-slate-800 capitalize">
              {result.skin_type || 'N/A'}
            </span>

          </div>


          {/* Gender */}

          <div className="bg-white rounded-lg border border-emerald-100 p-2">

            <span className="block text-[9px] uppercase font-bold text-slate-400">
              Gender
            </span>

            <span className="text-xs font-black text-slate-800 capitalize">
              {result.gender || 'N/A'}
            </span>

          </div>

        </div>


        {/* ----------------------------------------------------
            PERSONAL QUERY
            ---------------------------------------------------- */}

        {result.personal_query && (

          <div className="bg-white rounded-lg border border-emerald-100 p-2.5">

            <div className="flex items-center gap-1.5 mb-1">

              <MessageSquareText className="w-3.5 h-3.5 text-emerald-600" />

              <span className="text-[9px] uppercase font-bold text-slate-400">
                Personal Query
              </span>

            </div>

            <p className="text-[11px] text-slate-600 leading-relaxed">
              {result.personal_query}
            </p>

          </div>

        )}

      </div>


      {/* ======================================================
          PERSONALIZED ASSESSMENT
          ====================================================== */}

      <div className="bg-slate-900 rounded-xl border border-slate-800 p-4 text-slate-200">

        <div className="flex items-center gap-2 mb-2">

          <Sparkles className="w-4 h-4 text-emerald-400" />

          <span className="text-[10px] font-black text-emerald-400 uppercase tracking-wider">
            Personalized Assessment
          </span>

        </div>


        <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-wrap">

          {personalizedAssessment}

        </p>

      </div>


      {/* ======================================================
          WHAT YOU SHOULD DO
          ====================================================== */}

      <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-4">

        <div className="flex items-center gap-2 mb-2">

          <CheckCircle2 className="w-4 h-4 text-emerald-600" />

          <span className="text-[10px] font-black text-emerald-700 uppercase tracking-wider">
            What You Should Do
          </span>

        </div>


        <p className="text-xs text-slate-600 leading-relaxed whitespace-pre-wrap">

          {personalizedAction}

        </p>

      </div>


      {/* ======================================================
          PROBABILITY DISTRIBUTION
          ======================================================
          
          This section displays the complete output of the
          six-class CNN model.
          
          Example:
          
          Acne       95.2%
          Blackheads  1.8%
          Clear Skin  0.7%
          ...
          
          These probabilities are also used by the backend
          comparison module to calculate before/after changes.
          ====================================================== */}

      <div className="space-y-2.5 pt-1">

        <div className="flex items-center justify-between">

          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">

            6-Class Probability Distribution

          </span>

        </div>


        {probabilityEntries.map(
          ({
            concern,
            probability,
          }) => {

            // Convert model probability to percentage.

            const percent =
              (
                probability * 100
              ).toFixed(1);


            // Highlight the highest-probability class.

            const isPrimary =
              concern.toLowerCase() ===
              primaryConcern
                .toLowerCase();


            return (

              <div
                key={concern}
                className="space-y-1"
              >


                {/* ------------------------------------------
                    LABEL + PERCENTAGE
                    ------------------------------------------ */}

                <div className="flex justify-between text-xs font-semibold">

                  <span
                    className={
                      isPrimary
                        ? 'text-slate-900 font-bold capitalize'
                        : 'text-slate-500 capitalize'
                    }
                  >
                    {concern}
                  </span>


                  <span
                    className={
                      isPrimary
                        ? 'text-emerald-600 font-bold'
                        : 'text-slate-400'
                    }
                  >
                    {percent}%
                  </span>

                </div>


                {/* ------------------------------------------
                    PROGRESS BAR
                    ------------------------------------------ */}

                <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden border border-slate-200">

                  <div
                    className={
                      `h-full rounded-full transition-all duration-500 ${
                        isPrimary
                          ? 'bg-emerald-600'
                          : 'bg-slate-300'
                      }`
                    }
                    style={{
                      width: `${Math.min(
                        Math.max(
                          probability * 100,
                          0
                        ),
                        100
                      )}%`,
                    }}
                  />

                </div>

              </div>

            );
          }
        )}

      </div>


      {/* ======================================================
          AI DISCLAIMER
          ======================================================
          
          Important for evaluator clarity:
          
          The model predicts visual classes based on the
          training data. The output is not a medical diagnosis.
          ====================================================== */}

      <div className="bg-slate-50 border border-slate-200 rounded-xl p-3 flex items-start gap-2">

        <Info className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5" />

        <p className="text-[10px] text-slate-500 leading-relaxed">

          <span className="font-bold text-slate-600">
            AI Guidance:
          </span>{' '}

          The displayed probabilities represent the facial
          skin classification model's output. They are not
          clinically validated measurements or a medical
          diagnosis.

        </p>

      </div>

    </div>

  );
}